In [2]:
import torch

torch.manual_seed(1234)


In [3]:
torch.randn(4,4)

tensor([[-0.1117, -0.4966,  0.1631, -0.8817],
        [ 0.0539,  0.6684, -0.0597, -0.4675],
        [-0.2153,  0.8840, -0.7584, -0.3689],
        [-0.3424, -1.4020,  0.3206, -1.0219]])

In [4]:
torch.Tensor(4,4).uniform_(0,1)

tensor([[0.2837, 0.6567, 0.2388, 0.7313],
        [0.6012, 0.3043, 0.2548, 0.6294],
        [0.9665, 0.7399, 0.4517, 0.4757],
        [0.7842, 0.1525, 0.6662, 0.3343]])

In [5]:
torch.normal(mean=torch.arange(1.,11.),
            std=torch.arange(1,0,-0.1))

tensor([ 0.7389,  2.5494,  2.9921,  2.9869,  4.8777,  6.4369,  6.7274,  8.1902,
         9.0384, 10.0092])

In [6]:
torch.normal(mean=0.5,std=torch.arange(0.2, 0.6))

tensor([0.3275])

In [7]:
from torch.autograd import Variable

In [8]:
Variable(torch.ones(2,2),requires_grad =True)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [9]:
a,b = 12,23

x1 = Variable(torch.randn(a,b),
              requires_grad=True)
x2 = Variable(torch.randn(a,b),requires_grad=True)
x3 = Variable(torch.randn(a,b),requires_grad=True)
print(x1)
print(x2)
print(x3)

tensor([[-2.8333e-01, -5.6595e-01,  3.5662e-01, -4.5349e-01, -2.9714e-01,
         -1.5380e+00, -1.0248e+00, -3.7806e-01,  3.9102e-01,  5.1579e-01,
         -1.0042e+00,  9.8596e-01,  1.1334e+00,  8.5042e-01,  1.0534e+00,
          3.6918e-01, -5.5194e-02, -6.1254e-01,  7.5001e-01, -7.3459e-01,
          4.6223e-01,  1.1759e+00,  2.1447e-01],
        [ 5.3620e-01,  1.3649e-01, -2.3332e+00,  1.5308e+00,  2.6799e-01,
          4.5048e-01, -2.7250e-01, -1.7399e+00,  1.2993e-01, -5.6299e-01,
         -2.8294e-01,  7.3103e-02, -1.3880e+00, -2.6779e-01, -1.2537e-01,
         -1.5038e+00, -3.2867e-01,  4.3601e-01, -1.4770e+00, -1.2222e+00,
         -2.7464e-01, -3.4499e-01, -7.1620e-01],
        [ 5.7811e-01,  3.8052e-01, -1.4538e+00, -2.6740e+00,  1.5984e+00,
          8.0214e-01, -3.5115e-01, -6.7004e-02, -5.3376e-02, -8.3154e-01,
          1.4689e+00,  1.2647e+00, -2.7527e-01, -1.3254e-01,  1.0621e-01,
          9.2395e-02, -1.1821e+00,  2.1294e-01,  1.5495e-01, -6.5262e-01,
          7.17

         -7.7055e-01,  1.2134e+00,  8.0275e-01]], requires_grad=True)
tensor([[-0.4904,  0.2571, -0.2913, -0.6594, -1.3994, -0.5482,  0.6185, -1.0135,
         -0.6152, -0.4278,  0.2729, -0.5790,  0.0437,  1.0218,  1.0363,  1.2032,
         -0.1005, -0.8075,  0.3934, -0.6425,  0.2323,  0.7118,  0.1631],
        [-0.9765, -0.2103, -0.9933, -0.2486, -0.6136, -0.8202,  2.1842, -0.4091,
         -0.0667,  1.0655,  0.5185, -0.8217, -1.6376, -0.5362, -0.1288,  0.9668,
          0.2971,  0.2009, -0.6132, -1.2794, -0.4037,  0.0097, -0.4733],
        [ 1.2124, -0.1739, -0.7859, -0.6041, -0.2325,  1.0328, -0.3480,  1.4594,
         -0.0560, -1.2836,  0.7126,  1.1081,  0.0047,  0.6673, -0.5581, -0.9543,
          0.2181,  2.0906,  0.4160, -1.3930, -0.5809,  1.4967,  1.2538],
        [ 1.2667, -0.0936,  0.1063, -0.0317, -0.0646, -1.9279,  1.5847,  0.7670,
         -0.9860,  0.5260,  0.8361,  0.0282, -0.9293,  0.0598, -1.8229, -1.8741,
          0.2174,  0.8868, -0.4772,  1.1404,  0.6185,  1.5910, 

In [10]:
c = x1 * x2
d = a+ x3
e = torch.sum(d)
e.backward()
print(e)

tensor(3312.4048, grad_fn=<SumBackward0>)


In [11]:
x_data = [11.0, 22.0, 33.0]
y_data = [21.0, 14.0, 64.0]

w = Variable(torch.Tensor([1.0]), requires_grad=True)

print("predict before training",4,(4*w).data[0])

predict before training 4 tensor(4.)


In [12]:
def forward(x):
    return x *w
def loss(x,y):
    y_pred = forward(x)
    return (y_pred-y) * (y_pred-y)


In [13]:
for epoch in range(10):
    for x_val,y_val in zip(x_data, y_data):
        l = loss(x_val, y_val)
        l.backward()
        print('\tGrad: ',x_val, y_val, w.grad.data[0])
        w.data = w.data - 0.01 * w.grad.data
        w.grad.data.zero_()
    print('Progress:',epoch, l.data[0])

	Grad:  11.0 21.0 tensor(-220.)
	Grad:  22.0 14.0 tensor(2481.6001)
	Grad:  33.0 64.0 tensor(-51303.6484)
Progress: 0 tensor(604238.8125)
	Grad:  11.0 21.0 tensor(118461.7578)
	Grad:  22.0 14.0 tensor(-671630.6875)
	Grad:  33.0 64.0 tensor(13114108.)
Progress: 1 tensor(3.9481e+10)
	Grad:  11.0 21.0 tensor(-30279010.)
	Grad:  22.0 14.0 tensor(1.7199e+08)
	Grad:  33.0 64.0 tensor(-3.3589e+09)
Progress: 2 tensor(2.5900e+15)
	Grad:  11.0 21.0 tensor(7.7553e+09)
	Grad:  22.0 14.0 tensor(-4.4050e+10)
	Grad:  33.0 64.0 tensor(8.6030e+11)
Progress: 3 tensor(1.6991e+20)
	Grad:  11.0 21.0 tensor(-1.9863e+12)
	Grad:  22.0 14.0 tensor(1.1282e+13)
	Grad:  33.0 64.0 tensor(-2.2034e+14)
Progress: 4 tensor(1.1146e+25)
	Grad:  11.0 21.0 tensor(5.0875e+14)
	Grad:  22.0 14.0 tensor(-2.8897e+15)
	Grad:  33.0 64.0 tensor(5.6436e+16)
Progress: 5 tensor(7.3118e+29)
	Grad:  11.0 21.0 tensor(-1.3030e+17)
	Grad:  22.0 14.0 tensor(7.4013e+17)
	Grad:  33.0 64.0 tensor(-1.4455e+19)
Progress: 6 tensor(4.7966e+34)
	

In [14]:
print("predict before training",4,forward(4).data[0])

predict before training 4 tensor(-9.2687e+24)


In [15]:
x = Variable(torch.Tensor(4,4).uniform_(-4,5))
y = Variable(torch.Tensor(4,4).uniform_(-3,2))
z = torch.mm(x,y)
print(z.size())

torch.Size([4, 4])


In [17]:
z = Variable(torch.Tensor(4,4).uniform_(-5,5))
print(z)

tensor([[-2.5741, -4.2910,  1.4958,  3.3746],
        [-0.6658, -0.3624,  1.2819, -0.7361],
        [ 0.4200,  2.0541,  3.8482,  2.5524],
        [ 1.2238,  4.2838, -4.4571, -3.2921]])


In [18]:
print('Requires Gradient : %s'%(z.requires_grad))
print('Volatile: %s'%(z.volatile))
print('Gradient %s'%(z.grad))

Requires Gradient : False


c:\users\dell\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:2: UserWarning: volatile was removed (Variable.volatile is always False)
  


Volatile: False
Gradient None


In [19]:
mat1= torch.FloatTensor(4,4).uniform_(0,1)
mat1

tensor([[0.9065, 0.9649, 0.2669, 0.8926],
        [0.4426, 0.3603, 0.4807, 0.3700],
        [0.6377, 0.5379, 0.4975, 0.2898],
        [0.8037, 0.1902, 0.4931, 0.8293]])

In [20]:
mat2 = torch.FloatTensor(5,4).uniform_(0,1)
mat2

tensor([[0.2335, 0.1662, 0.6329, 0.0865],
        [0.2915, 0.9363, 0.7883, 0.9522],
        [0.0220, 0.0298, 0.6245, 0.6771],
        [0.2102, 0.6800, 0.5864, 0.2874],
        [0.9668, 0.8840, 0.9142, 0.3369]])

In [21]:
vec1 = torch.FloatTensor(4).uniform_(0,1)
vec1

tensor([0.5030, 0.2619, 0.9092, 0.9542])

In [22]:
mat1 + 10.5

tensor([[11.4065, 11.4649, 10.7669, 11.3926],
        [10.9426, 10.8603, 10.9807, 10.8700],
        [11.1377, 11.0379, 10.9975, 10.7898],
        [11.3037, 10.6902, 10.9931, 11.3293]])

In [23]:
mat2 - 0.20

tensor([[ 0.0335, -0.0338,  0.4329, -0.1135],
        [ 0.0915,  0.7363,  0.5883,  0.7522],
        [-0.1780, -0.1702,  0.4245,  0.4771],
        [ 0.0102,  0.4800,  0.3864,  0.0874],
        [ 0.7668,  0.6840,  0.7142,  0.1369]])

In [24]:
mat1+vec1

tensor([[1.4094, 1.2268, 1.1761, 1.8468],
        [0.9456, 0.6222, 1.3899, 1.3242],
        [1.1407, 0.7999, 1.4067, 1.2440],
        [1.3067, 0.4521, 1.4023, 1.7835]])

In [25]:
mat2+vec1

tensor([[0.7364, 0.4281, 1.5421, 1.0407],
        [0.7945, 1.1983, 1.6975, 1.9064],
        [0.5249, 0.2917, 1.5337, 1.6313],
        [0.7132, 0.9419, 1.4956, 1.2416],
        [1.4698, 1.1459, 1.8234, 1.2912]])

In [26]:
mat1 + mat2

RuntimeError: The size of tensor a (4) must match the size of tensor b (5) at non-singleton dimension 0

In [27]:
mat1 * mat1

tensor([[0.8217, 0.9309, 0.0712, 0.7967],
        [0.1959, 0.1298, 0.2311, 0.1369],
        [0.4066, 0.2894, 0.2475, 0.0840],
        [0.6459, 0.0362, 0.2432, 0.6877]])

In [28]:
from torch.distributions.bernoulli import Bernoulli

In [29]:
dist = Bernoulli(torch.tensor([0.3,0.6,0.9]))


In [32]:
dist.sample()

tensor([1., 0., 1.])

In [33]:
from torch.distributions.laplace import Laplace

In [34]:
dist = Laplace(torch.tensor([10.0]),torch.tensor([0.990]))
dist

Laplace(loc: tensor([10.]), scale: tensor([0.9900]))

In [35]:
dist.sample()

tensor([10.2443])